### ISSUE TITLE
Type mismatch in IDs make DATAFilter delete and create semantically identical objects

### ISSUE THREAD

**Issue by Tif-tof** [3lvis/DATAFilter#10]
If there is a type mismatch for the identifier in what is in the JSON from what is in the NSManagedObject definition, DATAFilter will fail to see that the objects are identical and will delete and recreate it.

For example, if such JSON is returned (if `localKey` is `remoteID` and `remoteKey` is `remoteID`):

```
[
  {
    "id": 30,
    ...
  }
]
```

And in the `NSManagedObject` definition, `remoteID` is of type string and has the value `"30"`, what I described above will happen (Because in the JSON, the identifier will be of type `NSNumber` and in the NSManagedObject of type `NSString`)

The method responsible for this seems to be `[+DATAFilter changes:inEntityNamed:localKey:remoteKey:context:predicate:inserted:updated:]`, on the line `[intersection intersectSet:[NSSet setWithArray:fetchedObjectIDs]];`
The `NSSet` will use the method `isEqual` and determines that a `NSNumber` can't be equal to a `NSString` (In my example)

I can submit a pull request that fixes the issue by always converting all identifiers (remote and local) to `NSString` prior to doing the intersection (using `[-NSObject description]`. What do you think?

**Comment by 3lvis** [comment]
Hi @Tif-tof,

Thanks for taking the time on writing such detailed issue, I see what's going on here, but I have to ask, is there a reason why do you have numbers in your JSON and strings in your app? 

I understand how we could fix your issue here but I would like to understand if this is a common requirement before making a change like this one.

Thanks!

**Comment by stephane-fueled** [comment]
Hi @3lvis

In my case, this is because I know the IDs are going to be strings at some point (backend is still being developed), thus I made it so I don't have to change it afterwards.
I can think of a few use cases where this could be useful (they are edge cases though, to be honest), on top of mine:
- When you don't have control over the backend and the IDs could just be anything at any point in time
- When you want to have a base object which has the ID definition, but this ID could vary in type between subclasses of that base object (Pretty sure some backend could have those consistency issues)

Personally, I also believe that the IDs 30 (number) and "30" (String) should be considered the same semantically, since the meaning they deliver is the same for both (The way they are being parsed shoudn't matter)

Thanks

**Comment by 3lvis** [comment]
Hi again @stephane-fueled! 

The best approach for this sort of issues could be sanitizing your JSON so it's more consistent and can easily be processed by DATAFilter.

When we get JSON like this one we use this utility to clean up and remove inconsistencies called Minced.

At the moment it doesn't support normalizing the types of ids but I added a feature request :)

https://github.com/hyperoslo/Minced/issues/19

Thanks!
